### PR TITLE
Release fixes

### LINKED ISSUE #505: UI corruption at startup
CC @mahkoh 

Expected:

Actual:

Ctrl-L fixes the glitches.

```
gp@MacBook-Pro-Gregory ~/d/cmus ((5969d12...)|BISECTING) [1]> git bisect log
git bisect start
# good: [9d37708a93c9fadeebe0eb9f8f67310e4fe55156] Merge pull request #475 from mahkoh/set_priority3
git bisect good 9d37708a93c9fadeebe0eb9f8f67310e4fe55156
# bad: [04836a121a1cba1950cb35371e3f8e46bbad74e1] Merge branch 'get_opt' of https://github.com/mahkoh/cmus into mahkoh-get_opt
git bisect bad 04836a121a1cba1950cb35371e3f8e46bbad74e1
# skip: [99e98f7330fef891b18a3d09e8dad921f1be85da] Add some wrapper functions to pl.c
git bisect skip 99e98f7330fef891b18a3d09e8dad921f1be85da
# skip: [4ae58951734e69c5ffe33192e33c10cff16d10d2] Use pl wrappers in command_mode.c
git bisect skip 4ae58951734e69c5ffe33192e33c10cff16d10d2
# bad: [da54f6dc59e906387fc8d2c589a2ea4998542a8e] Rename pl_clear_pl to pl_clear_visible_pl
git bisect bad da54f6dc59e906387fc8d2c589a2ea4998542a8e
# bad: [7262540b61dc1d43607215faa18456669c9e07fc] Use pl wrapper functions in ui_curses.c
git bisect bad 7262540b61dc1d43607215faa18456669c9e07fc
# bad: [4b54422c1e80e67fe8353988b178578c569dc832] Restore "continue" feature
git bisect bad 4b54422c1e80e67fe8353988b178578c569dc832
# good: [3ebe81b815e8b3b535cb23dd1869e0fbfdb34385] Add convenience macro for select
git bisect good 3ebe81b815e8b3b535cb23dd1869e0fbfdb34385
# good: [4a2ae75b27a920a8487b04f9abf35eb1761298fe] Fix a memory leak in free_update_job
git bisect good 4a2ae75b27a920a8487b04f9abf35eb1761298fe
# bad: [8fec8b59aed2ff32363508a3b795ee1a9f7cd4a7] Change jobs to use the async interface
git bisect bad 8fec8b59aed2ff32363508a3b795ee1a9f7cd4a7
# good: [5969d122a2da7b0a85256d042887e8c2b91f4ed7] Add multi-thread track requests
git bisect good 5969d122a2da7b0a85256d042887e8c2b91f4ed7
# first bad commit: [8fec8b59aed2ff32363508a3b795ee1a9f7cd4a7] Change jobs to use the async interface
```

### PR DESCRIPTION
**Pull request by mahkoh**
Addresses the issues raised in #507 and some more.

Coincidentally 3a8091b might (or might not) fix #505.

### CODE REVIEW

**Comment by mahkoh** [comment]
The compilers on travis are too old (2011.)

File: ui_curses.c [hunk 1]
```diff
@@ -1840,7 +1840,7 @@ static void spawn_status_program(void)
 		free(argv[i]);
 }
 
-static sig_atomic_t ctrl_c_pressed = 0;
+static _Atomic int ctrl_c_pressed = 0;
```
Comment (mahkoh) [inline ui_curses.c]: There should be a static assertion somewhere here that checks that `_Atomic int` is lock free. Unfortunately clang is bugged and doesn't define the correct macros. We could assert it at runtime but that's probably overkill since `_Atomic int` will probably be lock free everywhere.

**Comment by mahkoh** [comment]
This should work now.

File: .travis.yml [hunk 2]
```diff
@@ -1,29 +1,42 @@
...
+    - if [ "$CC" = "clang" ]; then export CC="clang-3.8"; fi
+addons:
+    apt:
+        sources:
+            - ubuntu-toolchain-r-test
+            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
+            - sourceline: 'deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
+        packages:
+            - gcc-6
+            - clang-3.8
```
Comment (flyingmutant) [inline .travis.yml]: These are pretty bleeding edge versions. We should probably use something older in Travis, so that we will not get situations like «it compiles in Travis, but fails in SOME_POPULAR_DISTRO».

**Comment by flyingmutant** [comment]
FYI — this does not fix #505.

**Comment by mahkoh** [comment]
Changed to gcc5, clang3.7.
