### PR TITLE
Fixes hanging when terminal is closed while promting

### LINKED ISSUE #765: cmus hangs if the window is killed
---

1) Linux arch 4.14.11-1-ARCH #1 SMP PREEMPT Wed Jan 3 07:02:42 UTC 2018 x86_64 GNU/Linux

```
(paste output here)
```

2) `cmus --version`:
```
cmus v2.7.1
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  oss
  ao

```

open gnome-terminal
start cmus
press q
kill window

-> 100% cpu usage -> SIGKILL

### PR DESCRIPTION
**Pull request by nefthy**
Fixes #765

### CODE REVIEW

File: ui_curses.c [hunk 1]
```diff
@@ -1624,11 +1624,11 @@ int yes_no_query(const char *format, ...)
 	while (1) {
 		int ch = getch();
 
-		if (ch == ERR || ch == 0)
-			continue;
-		if (ch == 'y')
+		if (ch == 'y' || !cmus_running) {
```
Comment (flyingmutant) [inline ui_curses.c]: why do we treat `!cmus_running` as "yes"?

Comment (nefthy) [reply ui_curses.c]: Well !cmus_running means that  cmus should exit, because it received a SIGTERM for example or something along the lines. If we treat it as 'n' cmus gets zombified and continues playing in the background.

Comment (nefthy) [reply ui_curses.c]: if we ignore cmus_running altogether it, cmus falls in an endless loop with 100% cpu utilisation under the conditions described in #765

Comment (flyingmutant) [reply ui_curses.c]: `yes_no_query` can be called in different places, and "no" is a better default answer (in general). Imagine if `rm -rf /` when killed while prompting "are you sure" would treat that as "yes" :-)

This fix looks more like a workaround than a solution.

Comment (nefthy) [reply ui_curses.c]: yes you are right in part. But returning "no" is also not an option. As is cmus zombifies if we return "no".

To fix this issue we will have to refactor the API to:

```bool yes_no_query(const char const * msg, char * res)```

And then change all invocations to check if the function for success before using the result. I could do that, but I'd prefer if we could work this out ahead of time, so we don't have that much back and forth.

Comment (nefthy) [reply ui_curses.c]: Sorry the function signature above is total crap.
Point is we need three return values: yes, no, error

Comment (geek1011) [reply ui_curses.c]: Maybe return an enum and check that?

Comment (nefthy) [reply ui_curses.c]: Sure, I have already started making the necessary changes.

**Comment by nefthy** [comment]
Please review.
